layer.conf: Remove LICENSE_PATH
meta-variscite-imx/licenses/ is empty, causing an error in bitbake:

$ bitbake fsl-gui-image
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (bsp-imx8mn-var-som-5.2.24/build_xwayland/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 25381 at 2020-08-18 16:20:05.156195 ---
ERROR: Unable to parse Var <AVAILABLE_LICENSES[:=]>
Traceback (most recent call last):
  File "Var <AVAILABLE_LICENSES[:=]>", line 1, in <module>
  File "bsp-imx8mn-var-som-5.2.24/sources/poky/meta/classes/license.bbclass", line 275, in available_licenses(d=<bb.data_smart.DataSmart object at 0x7fa40ea75b70>):
         for lic_dir in lic_dirs:
    >        licenses += os.listdir(lic_dir)

bb.data_smart.ExpansionError: Failure expanding variable AVAILABLE_LICENSES[:=], expression was ${@' '.join(available_licenses(d))} which triggered exception FileNotFoundError: [Errno 2] No such file or directory: 'bsp-imx8mn-var-som-5.2.24/sources/meta-variscite-imx/licenses'


Signed-off-by: Nate Drude <nate.d@variscite.com>